"""Tests for the Sudoku solver and uniqueness-checking logic."""

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import sudoku_logic
from solver import count_solutions


def test_generated_puzzle_has_unique_solution():
    """A puzzle generated by generate_puzzle() should have exactly one solution."""
    puzzle, solution = sudoku_logic.generate_puzzle(clues=35)

    puzzle_copy = sudoku_logic.deep_copy(puzzle)
    num_solutions = count_solutions(puzzle_copy, limit=2)

    assert num_solutions == 1


def test_count_solutions_on_full_board():
    """A fully solved board should count as exactly one solution."""
    board = sudoku_logic.create_empty_board()
    sudoku_logic.fill_board(board)

    num_solutions = count_solutions(board, limit=2)

    assert num_solutions == 1


def test_count_solutions_stops_at_limit():
    """An empty board has many solutions; count_solutions should stop at the limit."""
    board = sudoku_logic.create_empty_board()

    num_solutions = count_solutions(board, limit=2)

    assert num_solutions == 2